### ISSUE TITLE
Are these two related？

### ISSUE THREAD

**Issue by xm-gh888** [zhe1994/GANs-for-Fitting-SDFs#1]
Hello
I found this paper on Google Academic: Approaching Signed Distance Field to a Mesh by Artistic Neural Networks.
I thought it was written very well, Are these two related？

**Comment by dairyfreeZ** [comment]
Hi,
Sorry for the late reply, I don't use github often.

> I found this paper on Google Academic: Approaching Signed Distance Field to a Mesh by Artistic Neural Networks.

Yes, that's my master thesis. 

> May I ask if you can provide the code?

I meant to upload the code but forgot. Then couple years later when I checked because of someone's ask, I couldn't find where I stored them : /.

The idea of the article is very straight forward though, I used a GAN to train the model for a fairly short time and the result looked pretty good already.

**Comment by dairyfreeZ** [comment]
Mark as resolved.
